kind: Deployment
apiVersion: apps/v1
metadata:
  name: hollow-edge-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hollow-edge-node
  template:
    metadata:
      labels:
        app: hollow-edge-node
    spec:
      containers:
        - name: mock-monitor
          image: harbor.dev.thingsdao.com/edgewize/mock-edge-metrics:v0.0.1
          command:
            - /root/nodeMetricsMocker
          args:
            - --cluster=edge-1
            - --gateway-endpoint=http://gateway-whizard-operated.kubesphere-monitoring-system.svc.cluster.local:9090
          resources:
            requests:
              cpu: 20m
              memory: 50M
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
        - name: hollow-edgecore
          image: harbor.dev.thingsdao.com/edgewize/edgemarks:v1.13.0-taint5
          command:
            - edgemark
          args:
            - --token=$(TOKEN)
            - --name=$(NODE_NAME)
            - --http-server=https://172.31.18.9:30272
            - --websocket-server=172.31.18.9:30271
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokensecret
                  key: tokendata
          resources:
            requests:
              cpu: 20m
              memory: 50M
          securityContext:
            privileged: true
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
